datadump:
  location:
    authors: <author-location>
    works: <works-location>

spring:
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: recreate
      request:
        timeout: 20s
      connection:
        connect-timeout: 10s
        init-query-timeout: 20s

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: <db-id>
  region: asia-south1
  keyspace: main
  application.token: <token>